////CS Q&A
const csquestions = [
    "What is a peripheral?",
    "What is soft copy?",
    "What is hard copy?",
    "What is footprint?",
    "What is a display?",
    "What is a pixel?",
    "What is resolution?",
    "What is a low-resolution display?",
    "What is a high-resolution display?",
    "What is a monochrome image?",
    "What is bit depth?",
    "What is a portrait display?",
    "What is a landscape display?",
]

const csanswers = [
    "An external device connected to a computer",
    "Information and data that is virtual",
    "Information and data that is physical",
    "The space taken up by a peripheral",
    "An electronic device that outputs information via a screen or projection",
    "An illuminated dot",
    "The number of pixels in a display",
    "A display with a small number of pixels",
    "A display with a large number of pixels",
    "An image made of two colors normally black and white",
    "The number of bits used for one pixel",
    "Display with ratio of width to height of 4:3",
    "Display with ratio of width to height of 16:9"

]
////Math Q&A
const mathquestions = [
    "1 + 1",
    "2 + 2",
    "3 + 3",
    "4 + 4",
]

const mathanswers = [
    "2",
    "4",
    "6",
    "8",
]
////Morse Code Q&A
const mcquestions = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
]

const mcanswers = [
    ".-",
    "-...",
    "-.-.",
    "-..",
    ".",
    "..-.",
    "--.",
    "....",
    "..",
    ".---",
    "-.-",
    ".-..",
    "--",
    "-.",
    "---",
    ".--.",
    "--.-",
    ".-.",
    "...",
    "-",
    "..-",
    "...-",
    ".--",
    "-..-",
    "-.--",
    "--..",
]