////CS Q&A
const csquestions = [
    "What is a peripheral?",
    "What is soft copy?",
    "What is hard copy?",
    "What is footprint?",
    "What is a display?",
    "What is a pixel?",
    "What is resolution?",
    "What is a low-resolution display?",
    "What is a high-resolution display?",
    "What is a monochrome image?",
    "What is bit depth?",
    "What is a portrait display?",
    "What is a landscape display?",
]

const csanswers = [
    "An external device connected to a computer",
    "Information and data that is virtual",
    "Information and data that is physical",
    "The space taken up by a peripheral",
    "An electronic device that outputs information via a screen or projection",
    "An illuminated dot",
    "The number of pixels in a display",
    "A display with a small number of pixels",
    "A display with a large number of pixels",
    "An image made of two colors normally black and white",
    "The number of bits used for one pixel",
    "Display with ratio of width to height of 4:3",
    "Display with ratio of width to height of 16:9"

]
////Math Q&A
const mathquestions = [
    "1 + 1",
    "2 + 2",
    "3 + 3",
    "4 + 4",
]

const mathanswers = [
    "2",
    "4",
    "6",
    "8",
]
////Morse Code Q&A
const mcquestions = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
]

const mcanswers = [
    ".-",
    "-...",
    "-.-.",
    "-..",
    ".",
    "..-.",
    "--.",
    "....",
    "..",
    ".---",
    "-.-",
    ".-..",
    "--",
    "-.",
    "---",
    ".--.",
    "--.-",
    ".-.",
    "...",
    "-",
    "..-",
    "...-",
    ".--",
    "-..-",
    "-.--",
    "--..",
]

////Physics Q&A
const physicsquestions = [
    "What is a voltmeter?",
    "What are the effects of current?",
    "How do you calculate the resistance of a conductor?",
    "What is a resistor?",
    "What is Electromotive Force?",
    "What are magnetic materials?",
    "What are ferromagnetic substances?",
    "What are non-magnetic materials?",
    "What are the magnetic properties of iron?",
    "What are the magnetic properties of steel?",
    "What is Faraday's law of electromagnetic Induction?",
    "What is Lenz's law?"
]

const physicsanswers = [
    "It is a device which is used to measure the potential difference",
    "Heating effect, chemical effect and magnetic effect",
    "resistance = resistivity * length / cross-sectional area",
    "A resistor is a circuit component which is made from a substance having resistance",
    "Electromotive is the energy provided by a battery per coulomb of charge passing through it",
    "Materials that are attracted by a magnet or can be made into magnets",
    "Ferromagnetic substances are strongly attracted to the pole of a strong magnet",
    "Materials that are not attracted by a magnet or cannot be made into magnets",
    "1. Magnetically soft material. Easy to magnetise but loses it easily. 2. Induced magnetism is stronger. 3. Induced magnetism is lost when the permanent magnet is removed. 4. Used to make electromagnets. 5. Used in electric bells and magnetic relays.",
    "1. Magnetically hard material. Hard to magnetise but retains it longer. 2. Induced magnetism is weaker. 3. Induced magnetism is retained, though weaker, when the permanent magnet is removed. 4. Used to make permanent magnets. 5. Used in loudspeakers and electric meters.",
    "The induced current produces a magnetic field which opposes the change in the original magnetic flux"
]
////ICT Q&A 
const ictquestions = [
/////////////////////
//////Chapter 1//////
/////////////////////
    "What is a hardware?",
    "Give examples of external hardware devices.",
    "Give examples of internal hardware devices.",
    "What is a software?",
    "What are two types of softwares?",
    "What are system softwares?",
    "Give examples of system softwares.",
    "What is an application software?",
    "Give examples of application softwares.",
    "What is a computer system?",
    "What is a motherboard?",
    "What is a CPU?",
    "What is internal memory?",
    "What are two types of internal memories?",
    "What is volatile memory?",
    "What is non-volatile memory?",
    "What is RAM?",
    "What is ROM?",
    "What is BIOS?",
    "What are HDDs and SSDs?",
    "What is a graphics card / video card?",
    "What makes up a graphics card / video card",
    "What is a sound card?",
    "What is an operating system?",
    "What are different types of user interfaces?",
    "What is a CLI",
    "What is a GUI?",
    "What is a touchscreen interface?",
    // "What is a computer?",
    // "What is a desktop computer?",
    // "What is a laptop computer?",
    // "What is a tablet?",
    // "What is a smartphone?",
    // "What is a smartwatch?",
    // "What is a minframe computer?",
    // "State all the new technologies.",
    // "What is artificial intelligence biometrics?",
    // "What is artificial intelligence?",
    // "State and explain the two types of vision enhancement.",
    // "What are robotics?",
    // "What is quantum cryptography?",
    // "What is CAT?",
    // "What is 3D and holographic imaging?",
    // "What is virtual reality?",
/////////////////////
//////Chapter 2//////
/////////////////////
]

const ictanswers = [
    "Hardware is a tangible(can be touched picked up) physical component of a computer system.",
    "Monitor, keyboard, mouse and printer. External storage devices are memory stick, external HDD and etc.",
    "Processor, motherboard, RAM & ROM, video & sound card, internal HDD and SDD",
    "Programs that control computer systems",
    "System software and application software",
    "Programs that allow the hardware to run properly, control computer's hardware and application programs and communicate with user.",
    "OS, drivers, utilities, compiler, linker, interpreter",
    "Programs that allow the user to do specific tasks, designed to carry ouy tasks and can be general purpose software or custom-made software",
    "MS office, apps, gamer, editing software",
    "A set of integrated devices that input, output, processm and store data and information",
    "Main printed circuit board that holds and allows communication between many of the electronic components. To communicate and send signals to each other via the BUS network",
    "The central processing unit is a computer part that that interprets and executes the commands from the computer hardware and software",
    "Memory stored on computer data that is directly accessed by CPU.",
    "Random access memory and read only memory",
    "Memory that is not lost when computer power is turned off",
    "Memory that is lost when computer power is turned off",
    "Random access memory is an internal chip where volatile data is stored temporarily. Contents are lost when computer power is turned off",
    "Read only memory is used to store permanent non-volatile information which can only be read and cannot be altered. It is used to contain configuration data such as boot file",
    "Basic input output system is a program instruction code that tells computer what to do when turned on, checks hardware, loads the operating system OS into RAM and store date/time and system configuration in non-volatile chips",
    "They are main internal storage devices sometimes referred as secondary storage to store operating system, software and files",
    "They allow computer to send graphical information to display devices and conect to the motherboard",
    "A processing unit, memory unit, a cooling mechanism(heat sink, fan) and connection ports(vga, hdmi, dvi)",
    "It allows computer to produce and accept audio information, send to speaker and accept from microphone. It connects to the motherboard and is useful in the conversion of analogue data into digital and vice versa",
    "An operating system is a software program that manages computer resources and enables users to communicate with computer system",
    "Command line interface, graphical user interface and touchscreen interface",
    "Interface that types commands to tell the computer what to do and is used by technicians. It can also access everything on the computer system",
    "Interface that uses graphics to stand for the complicated actions, uses icons which can be selected by a mouse to select the icons. WIMP - windows icons menus pointers",
    "Interface used by phone and tablets with post-WIMP interaction",
]